apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "taskboard.name" . }}
  labels:
    {{- include "taskboard.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
